service: epic-resorts

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getResorts:
    handler: handler.getResorts
    environment: ${file(env.json)}
